export default {
    "+ Add Horizontal Giude": "+ Ajouter un guide horizontal",
    "+ Add Vertical Giude": "+ Ajouter un guide vertical",
    "2D View": "Vue 2D",
    "3D First Person": "3D Première personne",
    "3D View": "Vue 3D",
    "altitude": "altitude",
    "Altitude": "Altitude",
    "Areas": "Zones",
    "Cancel": "Annuler",
    "Catalog": "Catalogue",
    "Chain selected Elements to Group": "Chaîner les éléments sélectionnés au groupe",
    "Circular": "Circulaire",
    "color": "couleur",
    "Configure layer": "Configurer la couche",
    "Configure project": "Configurer le projet",
    "Confirm": "Confirmer",
    "Copy": "Copier",
    "Delete group and all Elements": "Supprimer le groupe et tous les éléments",
    "Delete layer": "Supprimer la couche",
    "Delete": "Supprimer",
    "Elements on layer {0}": "Éléments sur la couche {0}",
    "Elements": "Éléments",
    "Get Screenshot": "Obtenir une capture d'écran",
    "Group [{0}]": "Groupe [{0}]",
    "Group's Barycenter": "Barycentre du groupe",
    "Group's Elements": "Éléments du groupe",
    "Groups": "Groupes",
    "Guides": "Guides",
    "height": "hauteur",
    "Holes": "Trous",
    "Horizontal": "Horizontal",
    "Items": "Articles",
    "Last Selected": "Dernier sélectionné",
    "Layer config": "Configuration de la couche",
    "Layer": "Couche",
    "Layers": "Couches",
    "Length": "Longueur",
    "Lines": "Lignes",
    "Load project": "Charger le projet",
    "Mouse X Coordinate": "Coordonnée X de la souris",
    "Mouse Y Coordinate": "Coordonnée Y de la souris",
    "Name": "Nom",
    "New Empty Group": "Nouveau groupe vide",
    "New Group from selected": "Nouveau groupe à partir de la sélection",
    "New layer": "Nouvelle couche",
    "New project": "Nouveau projet",
    "opacity": "opacité",
    "Open catalog": "Ouvrir le catalogue",
    "order": "ordre",
    "Pan": "Déplacer",
    "Paste": "Coller",
    "Project config": "Configuration du projet",
    "Properties: [{0}] {1}": "Propriétés : [{0}] {1}",
    "Prototype": "Prototype",
    "Reset": "Réinitialiser",
    "Rotation": "Rotation",
    "Save project": "Enregistrer le projet",
    "Save": "Enregistrer",
    "Scene Zoom Level": "Niveau de zoom de la scène",
    "Search Element": "Rechercher un élément",
    "Snap to Grid": "Aligner sur la grille",
    "Snap to Guide": "Aligner sur le guide",
    "Snap to Line": "Aligner sur la ligne",
    "Snap to Point": "Aligner sur le point",
    "Snap to Segment": "Aligner sur le segment",
    "texture": "texture",
    "thickness": "épaisseur",
    "Toggle Group Visibility": "Basculer la visibilité du groupe",
    "Un-chain all Group's Elements and remove Group": "Détacher tous les éléments du groupe et supprimer le groupe",
    "Un-chain Element from Group": "Détacher l'élément du groupe",
    "Undo (CTRL-Z)": "Annuler (CTRL-Z)",
    "Unselect": "Désélectionner",
    "Vertical": "Vertical",
    "width": "largeur",
    "Would you want to start a new Project?": "Voulez-vous commencer un nouveau projet ?",
    "Zoom in": "Zoomer",
    "Zoom out": "Dézoomer"
};
